2020-04-04 20:48:44,864 ERROR: Exception on /index [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "d:\python\lib\site-packages\flask\app.py", line 2241, in preprocess_request
    rv = func()
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\main\routes.py", line 18, in before_request
    db.session.commit()
  File "d:\python\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\python\lib\site-packages\sqlalchemy\orm\session.py", line 1036, in commit
    self.transaction.commit()
  File "d:\python\lib\site-packages\sqlalchemy\orm\session.py", line 510, in commit
    self.session.dispatch.after_commit(self.session)
  File "d:\python\lib\site-packages\sqlalchemy\event\attr.py", line 261, in __call__
    fn(*args, **kw)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\models.py", line 39, in after_commit
    for obj in session._changes['add']:
TypeError: 'NoneType' object is not subscriptable
2020-04-04 21:05:38,285 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
2020-04-04 21:06:55,370 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
2020-04-04 21:07:09,577 ERROR: Exception on /search [GET] [in d:\python\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\main\routes.py", line 148, in search
    current_app.config['POSTS_PER_PAGE'])
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\models.py", line 18, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\search.py", line 24, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "d:\python\lib\site-packages\elasticsearch\client\utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "d:\python\lib\site-packages\elasticsearch\client\__init__.py", line 1627, in search
    body=body,
  File "d:\python\lib\site-packages\elasticsearch\transport.py", line 362, in perform_request
    timeout=timeout,
  File "d:\python\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\python\lib\site-packages\elasticsearch\connection\base.py", line 244, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-04-04 21:09:49,708 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
2020-04-04 21:14:17,750 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
2020-04-04 21:35:36,871 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
2020-04-04 21:36:53,475 INFO: Microblog startup [in E:\Ç®À¤\Á·Ï°\python\testProject_032620\app\__init__.py:89]
